name: deploy web

on:
  workflow_dispatch:

jobs:
  deploy_website:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'web/.nvmrc'

      - name: build
        run: |
          cd web
          yarn && yarn build

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mqttx-web-dist
          path: web/dist/
          retention-days: 30
